package com.fureniku.metropolis.enums;

public enum DecorativeBuilderType {
    DECORATIVE,
    DECORATIVE_TOGGLE,
    DECORATIVE_ROTATABLE,
    DECORATIVE_ROTATABLE_TOGGLE,
    DECORATIVE_CONNECT_HORIZONTAL,
    DECORATIVE_CONNECT_FULL,
    DECORATIVE_CONNECT_ROTATABLE,
    DECORATIVE_CONNECT_HORIZONTAL_TOGGLE,
    DECORATIVE_CONNECT_FULL_TOGGLE,
    DECORATIVE_CONNECT_ROTATABLE_TOGGLE
}
